version: '3.8'

services:
  mysql:
    image: mysql:8.0-debian
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m2z-design

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '3305:80'
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  arangodb:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - '8529:8529'
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps

volumes:
  mysql:
  mongo:
  arangodb_data:
  arangodb_apps_data: