version: '3.8'

services:
  database-mysql:
    image: mysql:8.0-debian
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 25s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m2z-design

  database-mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  database-arango:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - '8529:8529'
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps

  generator-service:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      database-mysql:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: prod


volumes:
  mysql:
  mongo:
  arangodb_data:
  arangodb_apps_data: